# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "660d4f034af67793ec53f00c661e57dd94817a3d1ab978163fe6289e06f16fe3f8431496c8e4eff1b9729cc2c47e906b6afb933605034fc2b64829c33fb47d99";
      version = "1.0.343";

    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = t {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "04b7c0c90cb26d643a0b3e7e1ffa2d2d423e977c1454ee5ea7c2e75547ecbc113838df17b797902a975f5ea2184a81a45b605a4d82970805e2bbb02feebc578d";
      version = "2.4.0";

    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "741b37171bda8365fe7831474b696dc9e5f4e254338d58e6d0155ea1b9af292e5b8d2ed6a8a8a6fc6983771266e47e2cb3c65e40e81fd27a6ad2ac3d37195fe3";
      version = "1.10.0";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljsjs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljsjs";
      groupId = "thheller";
      sha512 = "3d0b79eff075c38389d9f3501c60bf91a28a6ee25fc0a2df3159b365eff556e2ec8499b69860783478705ea33ff18e85fc0150229d5725e58e96f362bdc777f1";
      version = "0.0.22";

    };
    paths = [ src ];
  }

  rec {
    name = "pathom/com.wsscode";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pathom";
      groupId = "com.wsscode";
      sha512 = "56e2125d20f6704f802830f0698e90889fcbd9a315d1835141b132303f7b3043277ded8d120037b09d4b90f7e73adf03a89e0017277a7e018cbedaee30ad909c";
      version = "2.2.31";

    };
    paths = [ src ];
  }

  rec {
    name = "icu4j/com.ibm.icu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "icu4j";
      groupId = "com.ibm.icu";
      sha512 = "07d14b637c4a2975f44d0d70eb8b85ed7b4fa33ba2254a4774b0a3474de20c3ccd5530439a9f2a12a38437400ba361f52a07c4f1c3b7a771798cf9139d7f8ae7";
      version = "68.2";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "da30a716770795fce390e4dd340a8b728f220c6572383ffef55bd5839655d5611fcc06128b2144f6cdcb36f53072a12ec80b04afee787665e7ad0b6e888a6787";
      version = "1.15";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "e02d7baec926e0e0a7d9c71f09fee627fbde59ae7f3cbd4abcdf0533c8a87fba8c7cf4503df34bf33777063f4b6353a022552fd003fdbea9fad5752d53609bb8";
      version = "1.0.0";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-test-display/com.bhauman";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-test-display";
      groupId = "com.bhauman";
      sha512 = "d8aafc0214bb3719adbb2c957e6a7c939e0db65a0bf69c4369654f736882c3203a4eeb66670e1da18f60faa8bf97b094712472ce883a5a1a5f8dd52b8e413d96";
      version = "0.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "348c0ea0911bc0dcb08655e61b97ba040649b4b46c32a62aa84d0c29c245a8af5c16d44a4fa5455d6ab076f4bb5bbbe1ad3064a7befe583f13aeb9e32a169bf4";
      version = "0.2.44";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-http/cljs-http";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-http";
      groupId = "cljs-http";
      sha512 = "dd2938d8df8aa6a5597459d11097152de3f5e0f38508aef8328b8de173355f81b0ac2eef215955090de4a9c50b21c0ae6b51e85791d4358aa3ec659be58437df";
      version = "0.1.46";

    };
    paths = [ src ];
  }

  rec {
    name = "eql/edn-query-language";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "eql";
      groupId = "edn-query-language";
      sha512 = "b3ddcd9bad0b9effa8a00add3041fbbde352f36c06d5491e139181160a459d0b71ad2b4b5e5903dea5dfaad9a86f6d7014e1ade3f06843632aa9cd358f062323";
      version = "0.0.9";

    };
    paths = [ src ];
  }

  rec {
    name = "undertow-core/io.undertow";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "undertow-core";
      groupId = "io.undertow";
      sha512 = "d1dcc1236ac98518318bea1ab99037c4f447d431319dc9fa8a9bc830c2c3cee0f7b804cfb5492e71e68e96a128f259059de8d6404237572c78643c8824818b9b";
      version = "2.2.4.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "js/org.graalvm.js";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "js";
      groupId = "org.graalvm.js";
      sha512 = "30d24adb24db2fc67fcc06d2adb7a3603c439d98a427a034d903b80ff44f27260262ef7b4a7762473443f3068089583217b6c1459593a7e68225cb206608e676";
      version = "21.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "expound/expound";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "01c3c05c115ed06c558bf0e1ff088e414b1b49450cb67e1b7d08faf2e08c1d133e511e73c7a008b1d839dd7625541594eb29b45e97c0f9544d518d9c1e88e1ea";
      version = "0.8.6";

    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "18c97fb2b74c0bc2ff4f6dc722a3edec539f882ee85d0addf22bbf7e6fe02605d63f40c2b8a2905868ccd6f96cfc36a65f5fb70ddac31c6ec93da228a456edbd";
      version = "0.2.176";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.cli/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "1d88aa03eb6a664bf2c0ce22c45e7296d54d716e29b11904115be80ea1661623cf3e81fc222d164047058239010eb678af92ffedc7c3006475cceb59f3b21265";
      version = "1.0.206";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-fileupload/commons-fileupload";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-fileupload";
      groupId = "commons-fileupload";
      sha512 = "a8780b7dd7ab68f9e1df38e77a5207c45ff50ec53d8b1476570d069edc8f59e52fb1d0fc534d7e513ac5a01b385ba73c320794c82369a72bd6d817a3b3b21f39";
      version = "1.4";

    };
    paths = [ src ];
  }

  rec {
    name = "glogi/com.lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "glogi";
      groupId = "com.lambdaisland";
      sha512 = "f910c9ea010af5bf0ff93e0760879556c44e1d0f60dbd9fe5064d90047bcf61c15621ba3a80538c85ebf70ab07733fdf35c4bfabd5bba22c0dbcb5f63efa2d8e";
      version = "1.0.116";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-priority-map/tailrecursion";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-priority-map";
      groupId = "tailrecursion";
      sha512 = "788cbc93520c9a5155bb5c949fb49016caea292b4be4f1f349ace2269273727a637c5d023c8276381b6afba60ab70dd82d21f4caa03371b6659474f16a66cba9";
      version = "1.2.1";

    };
    paths = [ src ];
  }

  rec {
    name = "clojure-future-spec/clojure-future-spec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure-future-spec";
      groupId = "clojure-future-spec";
      sha512 = "7e71227dd4f2a5e9c6966fa6279ed66844721ffda2c66e8cdab2bc79a976c7070763baa2104a4337433fd8d991b7aa2e8ddf981974be664dce93410c47a68bb4";
      version = "1.9.0";

    };
    paths = [ src ];
  }

  rec {
    name = "encore/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "encore";
      groupId = "com.taoensso";
      sha512 = "a1ca4748c11f5af8fb94f9cae3a55752622a8f31eb1e95aea33abf6de34038aebc7b57c4fa855ab80b92739eb8f41b686b36a9dbe7bc2e7895bcb67957c36e0e";
      version = "2.115.0";

    };
    paths = [ src ];
  }

  rec {
    name = "fulcro-inspect/fulcrologic";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fulcro-inspect";
      groupId = "fulcrologic";
      sha512 = "814c6b783995ff6f691a1231ec23eff2027f684d3f1c0ab89f7ea44b7ce638e0d9b8cd032dc00d5d644244dbcf2540fa82f281f7251d500ac0b1f9b8c5ef1edb";
      version = "2.2.4";

    };
    paths = [ src ];
  }

  rec {
    name = "regex/org.graalvm.regex";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "regex";
      groupId = "org.graalvm.regex";
      sha512 = "9452d658af35f9fe061b39285c252d70015c94fd2ac77a75d0fdb92ff6c447564a90b199832e09ce03f55bd233f008d61814a10040d373432feabade8f8be92a";
      version = "21.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer.jvm/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "ce9c7b51fa61c12c539f3c5c1c7fa1caf123497553d4e566c13895312faad2d2657fe6e54fe88110a6c87accb10c4c3b6ccfa87a035a7321da6c859da1d192d0";
      version = "1.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-common/org.wildfly.common";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "wildfly-common";
      groupId = "org.wildfly.common";
      sha512 = "f99f23af23a1cc45035b87ab422affdb911769ee63dc5a1c9b3e7a39ebefee07542d2388118282b20113c196e28abce8f87cafc8b0213cdc692381edce035c46";
      version = "1.5.2.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "workspaces/nubank";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "workspaces";
      groupId = "nubank";
      sha512 = "349122f2eacd0175eaa808061d2387659e45998d43a7bae99f3c9991f20cb534da47f8305025ad6c526b039c7f4398b8f3537b256f61b2bf67dbc90e14c0c0d4";
      version = "1.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "react-dom/cljsjs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "react-dom";
      groupId = "cljsjs";
      sha512 = "825ee3b83a21f2ded10bb1e89d2f45bd6f9ed1beeda40080112c2275bb84d32526f39b4795db26ebb2665c07095bf8da1df25a697661587272e0b7ef10f7da10";
      version = "16.8.6-0";

    };
    paths = [ src ];
  }

  rec {
    name = "noencore/noencore";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "noencore";
      groupId = "noencore";
      sha512 = "111d8ab0c59a43b09cd4337b9dac2978b5210519c347c0c28ef52bd554e50d4182e6fa20d9389f3881ed0a8aa845150f10abc1891cba541a2daf43e842c86273";
      version = "0.3.4";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-cbor/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-cbor";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "575a00fec1760571403aaadbe0aa6c74f8bb01f40feae00741df6604e7c2bf199ac739a789bbd5d83af75ec6d9fcc55f5a1515b05aef33e0d3cc3046acad9e89";
      version = "2.10.2";

    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "ghostwheel/gnl";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ghostwheel";
      groupId = "gnl";
      sha512 = "833646ae9022b76ff0c1813a83a335d7c76f86be57a0e2bd547c6859db025a67f7141b58bc31a63fae6f13935485a29af1f077009783419e63a73ff574051c49";
      version = "0.3.9";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-cljs/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "526d3331857586ab7e8edb78795c375aaafe6dc3da24706663918a7dc38e25db7d0f554c334ec3be0334050d59d8616bd9cd6c9a90cf4bb4b33b1e0ea294d29c";
      version = "0.8.269";

    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "cf74661c5bc4658674397e498366ed12ce8b6f6cf51cdfa4cd0ce99415203028ec0bc4b59032a73ad4bf29421a643b2e6799fcd8a35f4f1e8676b3c04900a0b3";
      version = "0.0-20201211-3e6c510d";

    };
    paths = [ src ];
  }

  rec {
    name = "pretty/io.aviso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pretty";
      groupId = "io.aviso";
      sha512 = "2c4df86bb572cf028992a1a321178df65d0e681cbbc699db3a149fd0bcf8ad803643bf4e621a9b7793067f128934819371796468288cf5822924b2218711ccac";
      version = "0.1.33";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljs";
      groupId = "thheller";
      sha512 = "759a1ed007b14a36cff22dc5afefe4d57902b1fd3086c961591877efbe222381b1c9ab88c2b765ee30798324e96ff6c52dabfad8c84abd6ab61eaffcfebe1a2d";
      version = "2.15.3";

    };
    paths = [ src ];
  }

  rec {
    name = "graal-sdk/org.graalvm.sdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "graal-sdk";
      groupId = "org.graalvm.sdk";
      sha512 = "fca71a38aa19f0125d99cb67fb9f353261e4f99680f4e0208f29e0c3f37a2db886cff26f9c659dbec59b0650b49bd38f8fbc253bd5d90ae656ce1a07c64eb9b2";
      version = "21.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "51b9fa134f00514573996d4048b91362674d0d013aa163a639156510de92ceea0c2f26b5bf6532956b52f61fa160ca466192882209bb525fdb9af1ff7a7057ab";
      version = "1.10.879";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-bean/cljs-bean";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-bean";
      groupId = "cljs-bean";
      sha512 = "044bc011a7a63929b5b12e0d8bcea1aa7f69722359e90955a91590be62441a991aa3ba4117607028dbadf02e9e7da94079609ae50e91b699f301b7461f752ffc";
      version = "1.5.0";

    };
    paths = [ src ];
  }

  rec {
    name = "component/com.stuartsierra";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "component";
      groupId = "com.stuartsierra";
      sha512 = "0e373b24c2b85cb7a199bc0a4d0b72c77ff3024fe87bd244a49a9feab782a098a62f449ceacb42594d08604b7d63edcf1869a8ce18d0303d315592a676095180";
      version = "0.3.2";

    };
    paths = [ src ];
  }

  rec {
    name = "yuicompressor/com.yahoo.platform.yui";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "yuicompressor";
      groupId = "com.yahoo.platform.yui";
      sha512 = "ba2588bd50eaa3005b1919daad9f9c86a33351ceb9b7b5f0a9a498a548cc523e99f9345917a64303f8e23925feea226386d3eac01f640f788d1be4c7cf0315e0";
      version = "2.4.8";

    };
    paths = [ src ];
  }

  rec {
    name = "highlight/cljsjs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "highlight";
      groupId = "cljsjs";
      sha512 = "272029c9659b980b9842586495ed4a98353fdea461e179aa4d775db1d0068c12621eb3d0d701e0974b1efc69c9f648ed95006ecd2ea06176d1e03fb0f0f45bf6";
      version = "9.12.0-2";

    };
    paths = [ src ];
  }

  rec {
    name = "spec-coerce/spec-coerce";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec-coerce";
      groupId = "spec-coerce";
      sha512 = "76fded8a8f1d597b4dc91900b66957b4a717bf61d3c92a61bcdc107d7ad9d3384affda89a396d692a86f540e88ec5a7f37570e82ec833708e81a529d4daa6776";
      version = "1.0.0-alpha6";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-io/commons-io";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "6af22dffaaecd1553147e788b5cf50368582318f396e456fe9ff33f5175836713a5d700e51720465c932c2b1987daa83027358005812d6a95d5755432de3a79d";
      version = "2.10.0";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.namespace/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.namespace";
      groupId = "org.clojure";
      sha512 = "b599070c4696059128488ba0e12f5b1deb40ec27a985fb489a3c33e91e264ce8e96740c361c60abef5db465bf5036bfee1c3cd3d3ff87999925cfc9190340278";
      version = "0.2.11";

    };
    paths = [ src ];
  }

  rec {
    name = "fipp/fipp";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "4697699e9d5b792998e8c7ab6bf08d0d84c3e88793a0ff7024c10105f0db5703bccca9c43bb7fea00c1621af0d0604c89d623d74fde771a0d2e17835e1ab87b7";
      version = "0.6.24";

    };
    paths = [ src ];
  }

  rec {
    name = "jboss-logging/org.jboss.logging";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jboss-logging";
      groupId = "org.jboss.logging";
      sha512 = "c17b8882481c0cb8fbcdf7ea33d268e2173b1bfe04be71e61d5f07c3040b1c33b58781063f8ebf27325979d02255e62d1df16a633ac22f9d08adeb5c6b83a32a";
      version = "3.4.1.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "spec-inspec/com.wsscode";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec-inspec";
      groupId = "com.wsscode";
      sha512 = "6ddd3a1ae290be719f8ea235d962352a7949c38fe404cf43d45e6b975635f13f53525790d77bce5543151daeadea51849499a157ea541ac0c4aa761f040c1636";
      version = "1.0.0-alpha2";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "5055943790cea2c3abbacbe91e63634e6d2e977cd59b08ce102c0ee7d859995eb5d150d530da3848235b2b1b751a8df55cff2c33d43da695659248187ddf1bff";
      version = "2.10.2";

    };
    paths = [ src ];
  }

  rec {
    name = "asm/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "40614e658138f2eb95bc26999545f996794c622c4d68efb9e10093743504c4b58bf22590767bc6bd93b77cdfb202c507144ba867bbc8b54d74fe7621cbc55e3a";
      version = "5.2";

    };
    paths = [ src ];
  }

  rec {
    name = "fulcro/fulcrologic";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fulcro";
      groupId = "fulcrologic";
      sha512 = "94e5bd7f77fc0a1a24835911d81b66ab97f8e96bd899683b236a43a9e7872e36d6d84e1f0c79b615a3a0d4115946f25f47ef8b8cebad470375fbb1d69d246108";
      version = "2.6.16";

    };
    paths = [ src ];
  }

  rec {
    name = "react/cljsjs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "react";
      groupId = "cljsjs";
      sha512 = "79034721f5c44fc90887f6d31adc89794132c7e21a75439cb98bb2522e87fe906041c4b92aaf9dc349dcbe9352d0f22f8d9ec78817517eebce7de99ef760265c";
      version = "16.8.6-0";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-util/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-util";
      groupId = "thheller";
      sha512 = "803a068159276f5abf6d9cfa25f5c446c4c66d2eaec78393910cb2175b63a734c7c7effaf3064789608b1cf3899c287611c2d170fd78621193acc1fbbff1d5da";
      version = "0.7.0";

    };
    paths = [ src ];
  }

  rec {
    name = "instaparse/instaparse";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "instaparse";
      groupId = "instaparse";
      sha512 = "fe66379c8ca5692d8ab683d67e78754a2093127970ac0077ded743a669314b8ce8224cfd44e596e011a31f6f3cb6778895d1846afe162b77052d1218ee25bbfc";
      version = "1.4.10";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-js/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "bab8c657449a1d01e884923b77c5ef3d7a1a246c3ad1bd85a5b0c98b7952dbdeea97ce7d340ab50aa0dca647a1ef7eb846a52a1a4eecc55e1ff22145b8e820fe";
      version = "0.8.874";

    };
    paths = [ src ];
  }

  rec {
    name = "reitit-core/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reitit-core";
      groupId = "metosin";
      sha512 = "22c57f0bb0f5c398c9156b155d78575f05980ee09fa8a5744cafc24ba149f25bbf10c5ab1aa0ca3b9a3dd83c3d23f126b3257fc5395964128d73c7915b1fa549";
      version = "0.3.10";

    };
    paths = [ src ];
  }

  rec {
    name = "datascript-transit/datascript-transit";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "datascript-transit";
      groupId = "datascript-transit";
      sha512 = "dc307224c2a5c30776f0658ec8ec679d79d4daa4f9cee6b9f39c7f77ec5c39e2104e8da2a2eeee67a23aa5395b51357967dd0d825016cb7227f736b484377783";
      version = "0.3.0";

    };
    paths = [ src ];
  }

  rec {
    name = "truss/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "truss";
      groupId = "com.taoensso";
      sha512 = "601bdac92eb0432de228717d3feb7f8a24f484eaf8b93a98c95ee42a0d57bd3dd7d2929c21dadb3a9b43d5e449821d30bbcf4e5ae198dcb8c62ec9597ff57524";
      version = "1.5.0";

    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "b0be9cdb227ce189d74a2c0e9fe8cfe53ae5608f0e00382c6c12b0087672c6caeb96890beefd9f285ca7e0c7e4bee760299e14d48512e3e37f1f274838a1693d";
      version = "0.0-20201211-3e6c510d";

    };
    paths = [ src ];
  }

  rec {
    name = "fulcro/com.fulcrologic";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fulcro";
      groupId = "com.fulcrologic";
      sha512 = "772743f9d0a3303a1150f92de16d983c49bc30220ec8b031a3f588fba5e2781570d526cf9f1d2f01ebacde7ab84ee1959e1ff91e9cb3adc101a6a5cba386369b";
      version = "3.0.5";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-cache/org.clojars.mmb90";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-cache";
      groupId = "org.clojars.mmb90";
      sha512 = "4ec04b9d4eece3854ef1efb0d51981b132ac4e4068c1fc167b2a8e688500577cfccfc5dfbbdb8b3f8a45e72e814c4b8c2f0df89e6cc21d5f1be34f13ede63173";
      version = "0.1.4";

    };
    paths = [ src ];
  }

  rec {
    name = "rum/rum";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rum";
      groupId = "rum";
      sha512 = "1b864d6bc538ea0dc521f28ee8e25f26ac0e686caa6e1b2e3a2c6a7ed48b9d26a78d288a962997fd1cdf0a01acc318125672db59cbcec911ce7609f42d2b102a";
      version = "0.12.3";

    };
    paths = [ src ];
  }

  rec {
    name = "hiccup/hiccup";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "hiccup";
      groupId = "hiccup";
      sha512 = "034f15be46c35029f41869c912f82cb2929fbbb0524ea64bd98dcdb9cf09875b28c75e926fa5fff53942b0f9e543e85a73a2d03c3f2112eecae30fcef8b148f4";
      version = "1.0.5";

    };
    paths = [ src ];
  }

  rec {
    name = "react-grid-layout/cljsjs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "react-grid-layout";
      groupId = "cljsjs";
      sha512 = "af11546c731bfcf7cf81c09fc099be1fa561400166734794e48badf2bd7f080f072652ec9d37784e768f63d04d265b5793c143d08d72c2cee636d0fbbf6e3448";
      version = "0.16.6-0";

    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";

    };
    paths = [ src ];
  }

  rec {
    name = "linked/frankiesardo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "linked";
      groupId = "frankiesardo";
      sha512 = "d47354631d642a603f1f64e1bd872f623d8e6e7a8c40e968bcf124681585920c423a51f3388f6a4101c5f346b3e10a17b7e256da617ca0d1f19a25169dac46f7";
      version = "1.3.0";

    };
    paths = [ src ];
  }

  rec {
    name = "xnio-nio/org.jboss.xnio";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xnio-nio";
      groupId = "org.jboss.xnio";
      sha512 = "7f2c53222caf40793b1c956aa08ff3316a86577e6a79274050bcdf700b68546397b286e3d693c1b3036fe9175f54f76816cbf6a100ae67f9e6c20b4ca028e56d";
      version = "3.8.0.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "ghostwheel.logging/gnl";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ghostwheel.logging";
      groupId = "gnl";
      sha512 = "434e07c15572a29f0a5adb83da169500628f1747f2978f7517a07e4f8d91f2b94cd6698179919d52faef7084f7dab5113a0716797b2556d6d464f81c29a17c17";
      version = "0.3.9";

    };
    paths = [ src ];
  }

  rec {
    name = "truffle-api/org.graalvm.truffle";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "truffle-api";
      groupId = "org.graalvm.truffle";
      sha512 = "a0247b4c15020d27d39e2840b24a56afafbd385957b4844c2a6d3def9e3ce584780667b5c46bda7a7243c60ee69fdc3bf220f19e86534304a5557c2559259088";
      version = "21.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "boot-test/adzerk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "boot-test";
      groupId = "adzerk";
      sha512 = "5230f84f6c18ec4703607fa5d8e488c0cbb484681f7092d85bdbb835058df0baad654d33cd4eaabf1b6f53b213772f739ac850f2fd4cf110d3485e0a5aa8f7be";
      version = "1.1.2";

    };
    paths = [ src ];
  }

  rec {
    name = "devtools/binaryage";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "devtools";
      groupId = "binaryage";
      sha512 = "d4a890e5214c4136bb66b3397c3081fd61d3f15e231358bebebbca7fdade074aa6eab34634eabaac45bb92650d071bb7f98c124b19f9f0e0b38b0ff5e2e3e4bb";
      version = "1.0.2";

    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";

    };
    paths = [ src ];
  }

  rec {
    name = "orchestra/orchestra";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "orchestra";
      groupId = "orchestra";
      sha512 = "d10bc53b5b69bd9a12946360d1198f40140dcbe0e86b98507eb7a53b7c5449df2e9652d511330fced2a7f0e8a41be840169925a40e881deba40940e54bda2a8b";
      version = "2019.02.06-1";

    };
    paths = [ src ];
  }

  rec {
    name = "edamame/borkdude";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "edamame";
      groupId = "borkdude";
      sha512 = "c257ac529eec257133e265079b99cf14dbc6485174a916148c3dfe35009f31503b2403727dcb1947adc5c858cfd03962d786bdb0e877386a84f1fec37149ee91";
      version = "0.0.11-alpha.13";

    };
    paths = [ src ];
  }

  rec {
    name = "js-scriptengine/org.graalvm.js";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "js-scriptengine";
      groupId = "org.graalvm.js";
      sha512 = "190222663af351d5a63d51c1aa414dacdd7e73f97339697fa3a439df5976f631f2731bbea258c577922d1ce2535332f46f331b8f3bca9296fd3bf3c20a948fa4";
      version = "21.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "jboss-threads/org.jboss.threads";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jboss-threads";
      groupId = "org.jboss.threads";
      sha512 = "12d2b4c6c4f732a4b9437ae6e893087981aa2d829c9bad7089cd4cb10bccd7105e136f694e43a36e5bf234ca81294117fd9f6a07795f77c0f80d8f748c8fa529";
      version = "3.1.0.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "timbre/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "timbre";
      groupId = "com.taoensso";
      sha512 = "cbb47d1ba312ca5f8ffdb2953401e0b37b308529c49622d4eb57e1d128ae56768051a2e01264c3a3fe8ef1c8a8785fcc29bc9336ccc70e629f2ab432280e6d7f";
      version = "4.10.0";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "efe5483c188c8e6fb7327e2b312424de920b913ec9ca89580fddceb2a964de4ce75aab79d7d3671bb362b9af73a9e25a331abd4f53ce544d9b50f83a1a07adf4";
      version = "1.0.324";

    };
    paths = [ src ];
  }

  rec {
    name = "quoin/quoin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "quoin";
      groupId = "quoin";
      sha512 = "792e2861abd79747fde6cbd107424b2b471449cb555106070e2d073787e79ddbda66504b0a79caa713f21051d0826e6edb9deea68d811d983ab95289b150d612";
      version = "0.1.2";

    };
    paths = [ src ];
  }

  rec {
    name = "react-dom-server/cljsjs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "react-dom-server";
      groupId = "cljsjs";
      sha512 = "42973f7e4d3ad5047b09e9eb720198ef71b91077af5dc8e39da8d0606e2e29256551d61ad821228923988417423b76f1c0b5f5ec059cc9aafea0724d690cc8b9";
      version = "16.8.6-0";

    };
    paths = [ src ];
  }

  rec {
    name = "crypto-random/crypto-random";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "3520df744f250dbe061d1a5d7a05b7143f3a67a4c3f9ad87b8044ee68a36a702a0bcb3a203e35d380899dd01c28e01988b0a7af914b942ccbe0c35c9bdb22e11";
      version = "1.2.1";

    };
    paths = [ src ];
  }

  rec {
    name = "ghostwheel.unghost/gnl";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ghostwheel.unghost";
      groupId = "gnl";
      sha512 = "3ec38dd819ed950ff56e54463614aa919f573a1fbcf7cb73106598ef3b62bf7ff4fea3208a33c86bb6184566521e5891c002dc9f0b92f9d92bd8691eb49b5b43";
      version = "0.3.9";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-codec/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "38b9775a794831b8afd8d66991a75aa5910cd50952c9035866bf9cc01353810aedafbc3f35d8f9e56981ebf9e5c37c00b968759ed087d2855348b3f46d8d0487";
      version = "1.1.3";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-client/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-client";
      groupId = "thheller";
      sha512 = "b1f2ac82b31841d265af0939ecc0824e6ba8cc28d15b44c77f3abb305b5e88465b839915a222016c2ac8c7e2049d1daa2a3eebb9a58cdc9cf653bc56712b4ca7";
      version = "1.3.3";

    };
    paths = [ src ];
  }

  rec {
    name = "fulcro-incubator/fulcrologic";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fulcro-incubator";
      groupId = "fulcrologic";
      sha512 = "2c3a9ed8251bf1adb8652d36ce7b280b012caa278c150bc113291b7bf126da66552632ebd86b3e7fb1b5c0ff068c6ebc649c2c563facde2da8a321fd274a141f";
      version = "0.0.19";

    };
    paths = [ src ];
  }

  rec {
    name = "core.rrb-vector/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "7b6546bbd0ff8c7755382a5460029f57f562529ef66fc6ca473c4ba30d897ac5ff0aec8db737da9deeb732fccdd35c9c2317c256b7703e8e5804d1098e9bf77b";
      version = "0.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-drag-n-drop/cljs-drag-n-drop";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-drag-n-drop";
      groupId = "cljs-drag-n-drop";
      sha512 = "05521a2f94d18409f57cdcd3da71ea97304ef112c148a1c012d1fed78978f3871d6c5c3bc8a1ba2b57a8b999ad863b34b6031b595c1e4d0893a326d18d392742";
      version = "0.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "crypto-equality/crypto-equality";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";

    };
    paths = [ src ];
  }

  rec {
    name = "promesa/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "promesa";
      groupId = "funcool";
      sha512 = "488d4503a0c8dca1071659172bb18f98d374cfbbe6a0d63934462f355338285d9b6c7136d1b84b239a2ca878c120625cf3b59e0cf00c44cc722bcd4d24f12e2e";
      version = "4.0.2";

    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-client-config/org.wildfly.client";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "wildfly-client-config";
      groupId = "org.wildfly.client";
      sha512 = "3f442478c57f7dfac7039f6c7ae014bb2d45cdbd690ee631a3349edbca414adfe1984d065d1439f9b1546fa15fbd032c3a6bfe008f1ad50eef74201467b9f55f";
      version = "1.0.1.Final";

    };
    paths = [ src ];
  }

  (rec {
    name = "hickory/hickory";
    src = fetchgit {
      name = "hickory";
      url = "https://github.com/logseq/hickory";
      rev = "9c2c2f1fc2c45efaad906e0faabc3201278deeaa";
      sha256 = "0z1m6ai14fxrcw5xsj2kpk62k9am2cg9iji52sj6mis0ix17kka4";
    };
    paths = map (path: src + path) [
      "/src/clj"
        "/src/cljc"
        "/src/cljs"
    ];
  })

  rec {
    name = "persistent-sorted-set/persistent-sorted-set";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "persistent-sorted-set";
      groupId = "persistent-sorted-set";
      sha512 = "1ad5c9d14b14ce97476cbd6adf00bcfe6f7e245d3e2054a6947a99f1def4bf00ceac9ba6fc1e9dc3860d6b807e8d6d90df9450e8290351b3185e882d9e42a8f2";
      version = "0.1.4";

    };
    paths = [ src ];
  }

  rec {
    name = "cheshire/cheshire";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cheshire";
      groupId = "cheshire";
      sha512 = "5b2a339f8d90951a80105729a080b841e0de671f576bfa164a78bccc08691d548cff6a7124224444f7b3a267c9aca69c18e347657f1d66e407167c9b5b8b52cb";
      version = "5.10.0";

    };
    paths = [ src ];
  }

  rec {
    name = "tigris/tigris";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tigris";
      groupId = "tigris";
      sha512 = "fdff4ef5e7175a973aaef98de4f37dee8e125fc711c495382e280aaf3e11341fe8925d52567ca60f3f1795511ade11bc23461c88959632dfae3cf50374d02bf6";
      version = "0.1.2";

    };
    paths = [ src ];
  }

  (rec {
    name = "com.andrewmcveigh/cljs-time";
    src = fetchgit {
      name = "cljs-time";
      url = "https://github.com/logseq/cljs-time";
      rev = "5704fbf48d3478eedcf24d458c8964b3c2fd59a9";
      sha256 = "0s6p73s9iqqx8qhigpkrnzpg3900l99gzjfy9idhiv1647wln2i0";
    };
    paths = map (path: src + path) [
      "/src"
    ];
  })

  rec {
    name = "core.match/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.match";
      groupId = "org.clojure";
      sha512 = "52ada3bbe73ed1b429be811d3990df0cdb3e9d50f2a6c92b70d490a8ea922d4794da93c3b7487653f801954fc599704599b318b4d7926a9594583df37c55e926";
      version = "1.0.0";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "3481259c7a1eac719db2921e60173686726a0c2b65879d51a64d516a37f6120db8ffbb74b8bd273404285d7b25143ab5c7ced37e7c0eaf4ab1e44586ccd3c651";
      version = "1.3.6";

    };
    paths = [ src ];
  }

  rec {
    name = "fuzzy/com.wsscode";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fuzzy";
      groupId = "com.wsscode";
      sha512 = "8e51a292421be3e47940eef08696e5a93a236e9e2b952630dd8bc2e884bbcec19edb00391ccb96b4b5dc040ae7572954751c49bc700628f6eb94c3199da7d67e";
      version = "1.0.0";

    };
    paths = [ src ];
  }

  (rec {
    name = "borkdude/rewrite-edn";
    src = fetchgit {
      name = "rewrite-edn";
      url = "https://github.com/borkdude/rewrite-edn";
      rev = "edd87dc7f045f28d7afcbfc44bc0f0a2683dde62";
      sha256 = "1jvl37irhcndil2ndifx0jgigdrnsnya8y9h0dp4q09952v1r4iq";
    };
    paths = map (path: src + path) [
      "/src"
    ];
  })

  rec {
    name = "jsoup/org.jsoup";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsoup";
      groupId = "org.jsoup";
      sha512 = "1d169f1c509ba7c78f92240ea977f2f8d34b340860ebe2377fcce87e551ca54e5fb750491f7b32488e6db2652bbf96010decec4632a24e64f930a681cdb248a1";
      version = "1.9.2";

    };
    paths = [ src ];
  }

  (rec {
    name = "lread/rewrite-cljc";
    src = fetchgit {
      name = "rewrite-cljc";
      url = "https://github.com/lread/rewrite-cljc-playground";
      rev = "ba1e4255cd1c1fd09dbe2e90556bfa66d5459234";
      sha256 = "1kkd6p8bjczrrids3wsp60vp9bdsp12mjsi30fj9k91s62zxybfx";
    };
    paths = map (path: src + path) [
      "/src"
    ];
  })

  (rec {
    name = "datascript/datascript";
    src = fetchgit {
      name = "datascript";
      url = "https://github.com/logseq/datascript";
      rev = "de8df66e69ecd847c048f548fa0d5de0d4378bd0";
      sha256 = "1hw0qbmpk8c3fqj69qfwnh78x6p6l88yy3j39lr93ddpfmcy32ki";
    };
    paths = map (path: src + path) [
      "/src"
    ];
  })

  rec {
    name = "tongue/tongue";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tongue";
      groupId = "tongue";
      sha512 = "24cefb5e6b5f68442ce761f1bb5fc7d498f9fe39cb0502eef5cbe0d4e629ab8841ed1b007e0db4ed2bb538d35b4018909c280886a9466f8b2a57ff820048b4d2";
      version = "0.2.9";

    };
    paths = [ src ];
  }

  rec {
    name = "nrepl/nrepl";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "663906ff1c8768c4a73fa9f32619da4c244cc86c93d86e8439eb8de81c79486be5a04140c1df6199ba475b3a3e7fd36304faef8b330672dd644945820cc6eb67";
      version = "0.8.3";

    };
    paths = [ src ];
  }

  rec {
    name = "fulcro-garden-css/com.fulcrologic";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fulcro-garden-css";
      groupId = "com.fulcrologic";
      sha512 = "e7b8639979274340bddc5b7906acd08651e92027d11cbb6e313921616424e7bbb275d90b1bf8e6479390766bf765e7527aec64516f5b040b1b2161dc32b8bd1c";
      version = "3.0.6";

    };
    paths = [ src ];
  }

  rec {
    name = "xnio-api/org.jboss.xnio";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xnio-api";
      groupId = "org.jboss.xnio";
      sha512 = "eab8904c5e2f6071f076e5f68fc7520fb4e9f292df2cc03be4ac7834f52994e9f539b52be7509280f4fb49a4ded185732e8a50ffd3417e39b540d508db34ac5f";
      version = "3.8.0.Final";

    };
    paths = [ src ];
  }

  rec {
    name = "dommy/prismatic";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "dommy";
      groupId = "prismatic";
      sha512 = "753da7afbf48c1d203b09a71b865995879bfabf1473fe7b42ee0ce62673e75412265679962ca464b752b922104bcd30e08f8952f690f143bbd500d8697de0f51";
      version = "1.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-unshaded/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler-unshaded";
      groupId = "com.google.javascript";
      sha512 = "7f29e37c6de61cbafad10108fa2465a0140dd124f2e956a9552a6d0bea6125a758e8865490cbd3ce470599e137ec9e069ae436b3e5d7cd43d37f8a5009f4cf78";
      version = "v20210505";

    };
    paths = [ src ];
  }

  rec {
    name = "test.check/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "test.check";
      groupId = "org.clojure";
      sha512 = "68caa189e7292da5dfde92d795ce35ff1980108a579dc11ca618bf0e480101b8ded16fc8ab816b30f364afbccbb8f02fc9194271e7f5323b8042d468164ecb64";
      version = "1.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "reitit-frontend/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reitit-frontend";
      groupId = "metosin";
      sha512 = "5a3dae8315e2c138fd52e76717963870660a096d2b4e5c35336331e6bbd3d9766c17227139e39938836f6253a56c08d37219be71b7ed495f2a47fd0ff3930c17";
      version = "0.3.10";

    };
    paths = [ src ];
  }

  rec {
    name = "core.memoize/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "37308fcbbe64d0a2802917ef5a589075f81086d63e08c71a9a1b648b73dd362e5bdc8f756084fde1f4b1964ba82a6dc06b2119460281b7949a271d82e6a47a7e";
      version = "1.0.236";

    };
    paths = [ src ];
  }

  rec {
    name = "dependency/com.stuartsierra";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "dependency";
      groupId = "com.stuartsierra";
      sha512 = "339f26ada3faee517a60b48ba63911704b2c350af5bcc5401ca33830a2f8f01ed1315cae47c5b9fcee8dee47f96a65cbd5c9c336288287c155c7971f7dcd33c3";
      version = "0.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "camel-snake-kebab/camel-snake-kebab";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "camel-snake-kebab";
      groupId = "camel-snake-kebab";
      sha512 = "589d34b500560b7113760a16bfb6f0ccd8f162a1ce8c9bc829495432159ba9c95aebf6bc43aa126237a0525806a205a05f9910122074902b659e7fd151d176b1";
      version = "0.4.2";

    };
    paths = [ src ];
  }

  rec {
    name = "data.priority-map/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "fb2d703468fb6d5f28c38f25e8e7acdaf02d2fa1ac23c14a9ff065873e88c9b74e155e73e5069436d674d7ef8547f01bc9777b7ae3b9dcde67cbd327d4a20c06";
      version = "1.0.0";

    };
    paths = [ src ];
  }

  rec {
    name = "piggieback/cider";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "piggieback";
      groupId = "cider";
      sha512 = "b3183bbc81fe3a80c6e3c1c08fa0053b33dd9374c3199291aae14511b536e5de286dcc70e4642b6902d22200fb36b77b136eb0d0e7c5e84af2fb41e19fa2ce7a";
      version = "0.5.2";

    };
    paths = [ src ];
  }

  rec {
    name = "boot-cljs-test/crisptrutski";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "boot-cljs-test";
      groupId = "crisptrutski";
      sha512 = "eea310cdd415714d61d0b9810d5c320075694496511160c35ac5a33aea3f2c409e9996b13c9ee45acf58e510c2b31f8705ddec5de3940cb39c2d0e44cc988271";
      version = "0.2.2-20160402.204547-3";
      # broken
      url = "https://repo.clojars.org/crisptrutski/boot-cljs-test/0.2.2-SNAPSHOT/boot-cljs-test-0.2.2-20160402.204547-3.jar";
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-undertow/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-undertow";
      groupId = "thheller";
      sha512 = "9e03307416af711405f358aa828fe7a65e04e319ebe0f207ce5bac99cede456675a438a509cc71f6e71d35d3fcd43b4f187a9643356a1055401a32d3552403c9";
      version = "0.1.0";

    };
    paths = [ src ];
  }

  rec {
    name = "sci.impl.reflector/borkdude";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "sci.impl.reflector";
      groupId = "borkdude";
      sha512 = "c747fd347e6aba9578d105298b7c7402f53e8639d5c8e6dc83b127f3c413feeb1b9dead7405ac2c4345f02290902e8a2affbec749474481e9c9f19b3d049f18f";
      version = "0.0.1";

    };
    paths = [ src ];
  }

  rec {
    name = "sci/borkdude";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "sci";
      groupId = "borkdude";
      sha512 = "37da8d9cf3e22d736be7c20591a84ea8d679b69fe6897b359407a3073c5da3ac67b465e66a88f0f6e3c0e7183ae727cb6a5de6fc3d61acf2e6db5845f5aebfaf";
      version = "0.1.1-alpha.6";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-core/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "38d7214a3fc1b80ab55999036638dd1971272e01bec4cb8e0ee0a4aa83f51b8c41ba8a5850b0660227f067d2f9c6d75c0c0737725ea02762bbf8d192dc72febe";
      version = "1.9.4";

    };
    paths = [ src ];
  }

  rec {
    name = "core.cache/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "6e4e126f23b20120c50a4dbefbe1b3b9bd98f0a7b8fa83affa267ff7f0de09542d2727243859a1ea346bda5b782d4ae0110f6c2b169c298261707a1fdadaedb0";
      version = "1.0.207";

    };
    paths = [ src ];
  }

  rec {
    name = "meta-merge/meta-merge";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "meta-merge";
      groupId = "meta-merge";
      sha512 = "079339d69a18e88a7cf5ce37e29bf7d9b25c93011866fac3012b11444f9e3d69f4dc017a3e88ad20faa790b38e343e0b71e9e11c44028434da3f368f377e4458";
      version = "1.0.0";

    };
    paths = [ src ];
  }

  rec {
    name = "medley/medley";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "medley";
      groupId = "medley";
      sha512 = "40d9e4f570573e45ff99634d6446f0cd7f26443db0a616abbf5ea55ee731ca9d3245d212eb02070327ce4b208667699bcfcf81ad4ad6565bdc40f1b2970d5ed7";
      version = "1.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "hiccups/hiccups";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "hiccups";
      groupId = "hiccups";
      sha512 = "aea52df313d89fa846f8ebe5881c11329c17e096047fbbc9367d161092b64435f464e344b4f3cf88ce703c37aebf3aed9e817c82bb29a2b49fc83711d39f84bd";
      version = "0.3.0";

    };
    paths = [ src ];
  }

  rec {
    name = "garden/garden";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "garden";
      groupId = "garden";
      sha512 = "51e0bfaa18d249f9aa726b8dc91fc81048443c9b7e40064ac9c5fa6906c9e7009175245d317df5584ad40799216ded9e486656f4be5cdb3b8a12e2f02a4ca5af";
      version = "1.3.9";

    };
    paths = [ src ];
  }

  rec {
    name = "core.async/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "3a656c6f775940013a6b2e993bb60085246933c559d3c686fc7c2f5f82c70b672921d4bee964de2c31f6bf876cf3bc266ee39e918b6c310f5fd6254f65cb2064";
      version = "1.3.610";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-smile/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-smile";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "8998346f7039df868f3387d219efa0c04fc022a948d098296f3d7ac3f7a9a82bde6ec4a8f83b11994ad50318b5aca37781faacb1f20a65ba2ecc6d6d6eb9468e";
      version = "2.10.2";

    };
    paths = [ src ];
  }

  rec {
    name = "jaxb-api/javax.xml.bind";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "0c5bfc2c9f655bf5e6d596e0c196dcb9344d6dc78bf774207c8f8b6be59f69addf2b3121e81491983eff648dfbd55002b9878132de190825dad3ef3a1265b367";
      version = "2.3.0";

    };
    paths = [ src ];
  }

  ];
  }
